modLoader="javafml"
loaderVersion="[40,)"
license="Not specified"

[[mods]]
modId="erinium_faction"
version="1.0.0"
displayName="Erinium Faction"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.erinium_faction]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration