modLoader="javafml"
loaderVersion="[4,)"
license="Not specified"

[[mods]]
modId="erinium_faction"
version="1.0.0"
displayName="Erinium Faction"
displayURL="https://mcreator.net"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="MCreator"

# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "erinium_faction.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.erinium_faction]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.erinium_faction]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.erinium_faction]]
    modId="nexus_compiler"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration