modLoader="javafml"
loaderVersion="[4,)"
license="${mod_license}"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
updateJSONURL="https://raw.githubusercontent.com/JLSkyzer/EriniumFaction/main/src/main/resources/update.json"
displayURL="https://github.com/JLSkyzer/EriniumFaction"
credits="Thanks to everyone who supported the development of this mod!"
authors="${mod_authors}"
side = "BOTH"
description = '''${mod_description}'''
# Start of user code block mod configuration
# End of user code block mod configuration

[[mixins]]
    config = "erinium_faction.mixins.json"

# Start of user code block custom mixins
# End of user code block custom mixins

[[dependencies.erinium_faction]]
    modId="neoforge"
    type="required"
    versionRange="[21.1.176,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.erinium_faction]]
    modId="minecraft"
    type="required"
    versionRange="[1.21.1]"
    ordering="AFTER"
    side="BOTH"


[[dependencies.erinium_faction]]
    modId="nexus_compiler"
    type="optional"
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"


# Start of user code block dependencies configuration
# End of user code block dependencies configuration